global:
  domain: null
  imagePullSecret:
    {}
srv:
  bindings:
    saas-registry:
      serviceInstanceName: saas-registry
    service-manager:
      serviceInstanceName: service-manager
    auth:
      serviceInstanceName: xsuaa
  image:
    repository: <your-container-registry>/bookshop-srv
    tag: latest
  env:
    SPRING_PROFILES_ACTIVE: cloud
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 1G
    requests:
      ephemeral-storage: 1G
      cpu: 1000m
      memory: 1G
  health:
    liveness:
      path: /
    readiness:
      path: /
  envFrom:
    - configMapRef:
        name: "{{ .Release.Name }}-mtxs-configmap"
approuter:
  image:
    repository: <your-container-registry>/bookshop-approuter
    tag: latest
  env:
    TENANT_HOST_PATTERN: ^(.*)-{{ .Release.Name }}-approuter-{{ .Release.Namespace }}.{{ .Values.global.domain }} # change if expose.host is set
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 500m
      memory: 500M
  health:
    liveness:
      path: /
    readiness:
      path: /
  envFrom:
    - configMapRef:
        name: "{{ .Release.Name }}-approuter-configmap"
  bindings:
    auth:
      serviceInstanceName: xsuaa
backendDestinations:
  {}
service-manager:
  serviceOfferingName: service-manager
  servicePlanName: container
saas-registry:
  serviceOfferingName: saas-registry
  servicePlanName: application
  parametersFrom:
    - secretKeyRef:
        name: "{{ .Release.Name }}-saas-registry-secret"
        key: parameters
saasRegistryParameters:
  xsappname: bookshop
  appName: bookshop
  displayName: bookshop
  description: A simple CAP project.
  category: "CAP Application"
  appUrls:
    getDependencies: "/mt/v1.0/subscriptions/dependencies"
    onSubscription: "/mt/v1.0/subscriptions/tenants/{tenantId}"
    onSubscriptionAsync: true
    onUnSubscriptionAsync: true
    onUpdateDependenciesAsync: true
    callbackTimeoutMillis: 300000
sidecar:
  bindings:
    auth:
      serviceInstanceName: xsuaa
    service-manager:
      serviceInstanceName: service-manager
  image:
    repository: <your-container-registry>/bookshop-sidecar
    tag: latest
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 500m
      memory: 500M
  health:
    liveness:
      path: /health
    readiness:
      path: /health
xsuaa:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    xsappname: bookshop
    tenant-mode: shared
    oauth2-configuration:
      redirect-uris:
        - https://*.<your-cluster-domain>/**
