
---
spring:
  config.activate.on-profile: cloud
  sql.init.schema-locations: classpath:schema-h2.sql
cds:
  data-source:
    auto-config:
      enabled: false
  multi-tenancy:
    mtxs:
      enabled: true
  security.mock.users:
    - name: alice
      tenant: t1
      roles: [ cds.Subscriber, admin ]
    - name: bob
      tenant: t1
      roles: [ cds.ExtensionDeveloper, cds.UIFlexDeveloper ]
    - name: erin
      tenant: t2
      roles: [ cds.Subscriber, admin, cds.ExtensionDeveloper, cds.ExtensionDeveloper, cds.UIFlexDeveloperUIFlexDeveloper ]
---
spring:
  config.activate.on-profile: local-multitenancy
cds:
  multi-tenancy:
    mtxs.enabled: true
    sidecar.url: http://localhost:4005/ # in production mode overwrite with the URL from mta.yaml
